### ISSUE TITLE
Do not silently exit if an input metric does not exist

### ISSUE THREAD

**Issue by phijor** [metricq/metricq-combinator#6]
We came across an issue where `metricq-combinator` would exit with `status=1/FAILURE`, but no `ERROR` message was logged:

```
Jun 03 11:00:40 XXX systemd[1]: metricq-combinator-YYY.service: Main process exited, code=exited, status=1/FAILURE
Jun 03 11:00:40 XXX systemd[1]: metricq-combinator-YYY.service: Unit entered failed state.
Jun 03 11:00:40 XXX systemd[1]: metricq-combinator-YYY.service: Failed with result 'exit-code'. 
```

We figured out that this was caused by a typo in the configuration: an input metric was misspelled, and now named a metric that did not exist on the network.

TODO:

* [ ] figure out why the unknown metric led it to exit
* [ ] log this occurrence accordingly
* [ ] find a way to detect unknown metrics beforehand

**Comment by bmario** [comment]
This seems to be fixed already.
